from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from core import RetrievalResult
from core.query_engine import HybridSearch, Reranker
from core.response import AnswerGenerator, AnswerGeneratorError, GeneratedAnswer
from core.settings import load_settings
from core.trace import TraceContext
from observability.dashboard.services.data_service import DataService
from observability.logger import write_trace


TraceWriter = Callable[..., dict[str, Any]]


@dataclass(frozen=True)
class DashboardQueryResult:
    question: str
    results: list[RetrievalResult]
    trace: TraceContext
    rerank_applied: bool
    answer: GeneratedAnswer | None = None
    answer_error: str | None = None
    rerank_error: str | None = None


def render() -> None:
    import streamlit as st

    st.title("Knowledge Base Query")
    try:
        settings = load_settings("config/settings.yaml")
        service = DataService(settings)
        collections = service.list_collections()
    except Exception as error:
        st.error(f"Failed to load query service: {error}")
        return

    collection = st.selectbox("Collection", collections)
    dimension_warning = _dimension_warning(settings, service.collection_dimensions(collection))
    if dimension_warning:
        st.warning(dimension_warning)
    question = st.text_area("Question", placeholder="e.g. What is the price of the sea salt osmanthus latte?")
    top_k = st.number_input("Top K", min_value=1, max_value=50, value=settings.retrieval.top_k_final, step=1)
    generate_answer = st.checkbox("Generate LLM answer (calls the chat LLM configured in Settings)")

    if not st.button("Ask", type="primary"):
        st.info("Enter a question to retrieve the most relevant passages from the selected collection.")
        return
    if not isinstance(question, str) or not question.strip():
        st.warning("Please enter a question.")
        return

    spinner = "Searching and generating an answer..." if generate_answer else "Searching the knowledge base..."
    try:
        with st.spinner(spinner):
            if generate_answer:
                query_result = run_dashboard_answer(settings, question, collection, int(top_k))
            else:
                query_result = run_dashboard_query(settings, question, collection, int(top_k))
    except Exception as error:
        st.error(f"Query failed: {error}")
        return

    if not query_result.results:
        st.warning("No relevant passages found. Confirm that the document was ingested into this collection.")
        return

    if generate_answer:
        _render_answer(st, query_result)

    best = query_result.results[0]
    st.subheader("Best matching passage")
    st.write(best.text)
    st.caption(_source_caption(best))

    left, middle = st.columns(2)
    left.metric("Results", len(query_result.results))
    middle.metric("Rerank", "fallback" if query_result.rerank_error else ("applied" if query_result.rerank_applied else "disabled"))
    if query_result.rerank_error:
        st.warning(f"Rerank backend fell back to the original retrieval order: {query_result.rerank_error}")

    st.subheader("Retrieved passages")
    for index, result in enumerate(query_result.results, start=1):
        with st.expander(_result_label(index, result)):
            st.write(result.text)
            st.json(result.metadata, expanded=False)


def _render_answer(st: Any, query_result: DashboardQueryResult) -> None:
    if query_result.answer is not None:
        answer = query_result.answer
        st.subheader("LLM answer")
        st.markdown(answer.answer)
        sources = " · ".join(f"[{citation.id}] {citation.source}" for citation in answer.citations)
        st.caption(f"Generated by {answer.provider} · {answer.model} from {sources}")
        return
    if query_result.answer_error:
        if "API key" in query_result.answer_error:
            st.warning(f"{query_result.answer_error} Retrieval results are shown below.")
        else:
            st.error(f"{query_result.answer_error} Retrieval results are shown below.")


def run_dashboard_query(
    settings: Any,
    question: str,
    collection: str,
    top_k: int,
    search: Any | None = None,
    reranker: Any | None = None,
    trace_writer: TraceWriter = write_trace,
) -> DashboardQueryResult:
    _validate_query(question, top_k)
    trace = TraceContext(trace_type="query", metadata={"query": question, "collection": collection})
    try:
        results, rerank_applied = _retrieve(settings, question, collection, top_k, search, reranker, trace)
        trace.finish("success")
    except Exception as error:
        trace.record_stage("query.error", {"error": str(error)})
        trace.finish("failed")
        trace_writer(trace.to_dict(), path=_trace_path(settings))
        raise

    trace_writer(trace.to_dict(), path=_trace_path(settings))
    return DashboardQueryResult(
        question=question,
        results=results,
        trace=trace,
        rerank_applied=rerank_applied,
        rerank_error=_rerank_fallback_error(trace),
    )


def run_dashboard_answer(
    settings: Any,
    question: str,
    collection: str,
    top_k: int,
    llm: Any | None = None,
    search: Any | None = None,
    reranker: Any | None = None,
    trace_writer: TraceWriter = write_trace,
) -> DashboardQueryResult:
    _validate_query(question, top_k)
    trace = TraceContext(trace_type="query", metadata={"query": question, "collection": collection, "generate_answer": True})
    answer: GeneratedAnswer | None = None
    answer_error: str | None = None
    try:
        results, rerank_applied = _retrieve(settings, question, collection, top_k, search, reranker, trace)
        if results:
            try:
                answer = AnswerGenerator(settings, llm=llm).generate(question, results, trace=trace)
            except AnswerGeneratorError as error:
                answer_error = str(error)
                trace.record_stage("generation.error", {"error": answer_error})
        trace.finish("success")
    except Exception as error:
        trace.record_stage("query.error", {"error": str(error)})
        trace.finish("failed")
        trace_writer(trace.to_dict(), path=_trace_path(settings))
        raise

    trace_writer(trace.to_dict(), path=_trace_path(settings))
    return DashboardQueryResult(
        question=question,
        results=results,
        trace=trace,
        rerank_applied=rerank_applied,
        answer=answer,
        answer_error=answer_error,
        rerank_error=_rerank_fallback_error(trace),
    )


def _rerank_fallback_error(trace: TraceContext) -> str | None:
    for stage in trace.stages:
        details = stage.get("details") or {}
        if str(stage.get("name", "")).startswith("rerank") and details.get("fallback") and details.get("error"):
            return str(details["error"])
    return None


def _dimension_warning(settings: Any, stored_dimensions: int | None) -> str | None:
    expected = getattr(settings.embedding, "dimensions", None)
    if stored_dimensions is None or not isinstance(expected, int) or expected <= 0 or stored_dimensions == expected:
        return None
    provider = getattr(settings.embedding, "provider", "unknown")
    return (
        f"This collection stores {stored_dimensions}-dim vectors, but the current embedding provider "
        f"'{provider}' is configured with {expected} dimensions. Queries will fail until you re-ingest "
        f"the collection with the current embedding, or switch the embedding provider back."
    )


def _validate_query(question: str, top_k: int) -> None:
    if not isinstance(question, str) or not question.strip():
        raise ValueError("question must be a non-empty string")
    if not isinstance(top_k, int) or top_k <= 0:
        raise ValueError("top_k must be a positive integer")


def _retrieve(
    settings: Any,
    question: str,
    collection: str,
    top_k: int,
    search: Any | None,
    reranker: Any | None,
    trace: TraceContext,
) -> tuple[list[RetrievalResult], bool]:
    active_search = search or HybridSearch(settings)
    candidates = active_search.search(question, top_k=top_k, filters={"collection": collection}, trace=trace)
    active_reranker = reranker or Reranker(settings)
    results = active_reranker.rerank(question, candidates, trace=trace)
    rerank_applied = _rerank_enabled(settings) and bool(candidates)
    return results, rerank_applied


def _rerank_enabled(settings: Any) -> bool:
    rerank = settings.get("rerank", {}) if isinstance(settings, dict) else getattr(settings, "rerank", None)
    return bool(rerank.get("enabled", False)) if isinstance(rerank, dict) else bool(getattr(rerank, "enabled", False))


def _trace_path(settings: Any) -> str:
    observability = settings.get("observability", {}) if isinstance(settings, dict) else getattr(settings, "observability", None)
    value = observability.get("trace_path") if isinstance(observability, dict) else getattr(observability, "trace_path", None)
    return value if isinstance(value, str) and value else "logs/traces.jsonl"


def _source_caption(result: RetrievalResult) -> str:
    source = result.metadata.get("source_path") or result.metadata.get("source") or "unknown"
    chunk_index = result.metadata.get("chunk_index", "-")
    return f"Source: {source} · Chunk: {chunk_index} · Score: {result.score:.4f}"


def _result_label(index: int, result: RetrievalResult) -> str:
    source = result.metadata.get("source_path") or result.metadata.get("source") or "unknown"
    return f"{index}. {source} · score={result.score:.4f}"
